spring.application.name=rag
spring.ai.model.chat=ollama
spring.ai.ollama.chat.keep-alive=-1s
spring.ai.ollama.chat.num-ctx=2048
# The URL where Ollama is running
spring.ai.ollama.base-url=http://127.0.0.1:11434

# The model you want to use (must be pulled via 'ollama pull')
spring.ai.ollama.chat.model=ilsp/llama-krikri-8b-instruct:latest


# Optional: Adjust temperature (0.0 is deterministic, 1.0 is creative)
spring.ai.ollama.chat.temperature=0.7
telegram.bot.token=${TELEGRAM_TOKEN}
telegram.bot.name=${TELEGRAM_NAME}
